# SITE CONFIGURATION
title: How to Become a Hacker! # your site title
author: HackingProfessional # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/HTB" # the subpath of your site, e.g. /blog
url: "https://hackingprofessional.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Gerardo Eliasib - Gerh (Sephiroth)
  links:
    - https://www.facebook.com/gerh002
    - https://hackingprofessional.github.io/Security/
    - https://github.com/HackingProfessional
    - https://www.instagram.com/gerardo_rh97/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Learn hacking from 0 with HackTheBox

hero_img: posts/wall.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gerueda6@misena.edu.co # email for form submission

# twitter_username: # replace with your_twitter_username or comment to remove link from footer
github_username:  HackingProfessional # replace with your_github_username or comment to remove link from footer
instagram_username: gerardo_rh97 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: https-hackingprofessional-github-io-htb # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-WL2VVF7 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
